-- Lesson image cache.
--
-- Every illustration in the curriculum (signs, diagrams, atmospheric
-- heroes) is generated by Flux on Workers AI once, cached in R2, and
-- referenced by a stable slot key. Shortcode renderer reads this
-- table to resolve `[[image:KEY]]` -> R2 URL.
--
-- Schools can pre-render the full set; new lessons that introduce
-- new slot keys lazy-generate on first view (or on admin trigger).

CREATE TABLE lesson_image (
  id              TEXT PRIMARY KEY,
  slotKey         TEXT NOT NULL UNIQUE,   -- e.g. 'sign:stop', 'hero:night-rural'
  slotKind        TEXT NOT NULL,           -- 'sign' | 'hero' | 'diagram' | 'composition'
  prompt          TEXT NOT NULL,
  r2Key           TEXT NOT NULL,           -- 'lesson-images/sign/stop.jpg'
  widthPx         INTEGER NOT NULL,
  heightPx        INTEGER NOT NULL,
  vendor          TEXT NOT NULL,           -- '@cf/black-forest-labs/flux-1-schnell'
  generatedAt     INTEGER NOT NULL,
  bytes           INTEGER NOT NULL
);
CREATE INDEX idx_lesson_image_kind ON lesson_image(slotKind);
