-- 0057: Cached AI-generated SEO content ideas per school.
--
-- The SEO review panel suggests blog/guide topics a local family might
-- search — generated by the LLM from the school's state, city, and
-- programs, and cached here so the panel is instant and we only pay
-- for generation when the owner asks (or refreshes). One JSON blob per
-- org; regenerating overwrites it.
CREATE TABLE seo_topics (
  organizationId TEXT PRIMARY KEY NOT NULL REFERENCES organization(id) ON DELETE CASCADE,
  topicsJson     TEXT NOT NULL,   -- JSON array of {title, rationale, keyword}
  generatedAt    INTEGER NOT NULL
) STRICT;
