import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("features", "routes/features.tsx"),
  route("built-on-realism", "routes/built-on-realism.tsx"),
  route("start-a-school", "routes/start-a-school.tsx"),
  route("for-schools", "routes/for-schools.tsx"),
  route("for-families", "routes/for-families.tsx"),
  route("for-instructors", "routes/for-instructors.tsx"),
  route("states", "routes/states.tsx"),
  route("states/requests", "routes/states.requests.tsx"),
  route("why", "routes/why.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("login", "routes/login.tsx"),
  route("signup", "routes/signup.tsx"),
  route("logout", "routes/logout.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("api/auth/*", "routes/api.auth.tsx"),
  route("api/stripe/webhook", "routes/api.stripe.webhook.tsx"),
  route("api/internal/state-kb-seed/*", "routes/api.internal.state-kb-seed.tsx"),
  route("assets/*", "routes/assets.$.tsx"),
  route("sitemap.xml", "routes/sitemap[.]xml.tsx"),
  route("robots.txt", "routes/robots[.]txt.tsx"),
  route("schools/:slug", "routes/schools.$slug.tsx"),
  route("schools/:slug/enroll", "routes/schools.$slug.enroll.tsx"),

  route("admin", "routes/admin.tsx", [
    index("routes/admin._index.tsx"),
    route("students", "routes/admin.students.tsx"),
    route("students/new", "routes/admin.students.new.tsx"),
    route("students/:studentId", "routes/admin.students.$studentId.tsx"),
    route("instructors", "routes/admin.instructors.tsx"),
    route("instructors/new", "routes/admin.instructors.new.tsx"),
    route("instructors/:instructorId", "routes/admin.instructors.$instructorId.tsx"),
    route(
      "instructors/:instructorId/tax-doc/:docId.pdf",
      "routes/admin.instructors.$instructorId.tax-doc.$docId[.pdf].tsx",
    ),
    route("vehicles", "routes/admin.vehicles.tsx"),
    route("locations", "routes/admin.locations.tsx"),
    route("vehicles/:vehicleId", "routes/admin.vehicles.$vehicleId.tsx"),
    route(
      "vehicles/:vehicleId/photo.jpg",
      "routes/admin.vehicles.$vehicleId.photo[.jpg].tsx",
    ),
    route("schedule", "routes/admin.schedule.tsx"),
    route("schedule/board", "routes/admin.schedule.board.tsx"),
    route("board/socket", "routes/admin.board.socket.tsx"),
    route("schedule/new", "routes/admin.schedule.new.tsx"),
    route("schedule/series/new", "routes/admin.schedule.series.new.tsx"),
    route("schedule/series/:seriesId", "routes/admin.schedule.series.$seriesId.tsx"),
    route("programs", "routes/admin.programs.tsx"),
    route("programs/new", "routes/admin.programs.new.tsx"),
    route("programs/:programId", "routes/admin.programs.$programId.tsx"),
    route("payments", "routes/admin.payments.tsx"),
    route("payroll", "routes/admin.payroll.tsx"),
    route("payroll/:periodId", "routes/admin.payroll.$periodId.tsx"),
    route("payroll/:periodId/export.csv", "routes/admin.payroll.$periodId.export[.csv].tsx"),
    route("payroll/1099/:year.csv", "routes/admin.payroll.1099.$year[.csv].tsx"),
    route("dashboard/snapshot.csv", "routes/admin.dashboard.snapshot[.csv].tsx"),
    route("onboarding", "routes/admin._onboarding.tsx"),
    route("import", "routes/admin.import.tsx"),
    route("import/staff", "routes/admin.import.staff.tsx"),
    route("import/fleet", "routes/admin.import.fleet.tsx"),
    route("import/payments", "routes/admin.import.payments.tsx"),
    route("export.csv", "routes/admin.export[.csv].tsx"),
    route("reminders", "routes/admin.reminders.tsx"),
    route("library", "routes/admin.library.tsx"),
    route("library/import", "routes/admin.library.import.tsx"),
    route("library/media", "routes/admin.library.media.tsx"),
    route("library/places", "routes/admin.library.places.tsx"),
    route("library/installed/:installId", "routes/admin.library.installed.$installId.tsx"),
    route(
      "library/installed/:installId/lessons/:lessonId",
      "routes/admin.library.installed.$installId.lessons.$lessonId.tsx",
    ),
    route("settings", "routes/admin.settings.tsx"),
    route("settings/payments", "routes/admin.settings.payments.tsx"),
    route("settings/compensation", "routes/admin.settings.compensation.tsx"),
    route("settings/btw-flow", "routes/admin.settings.btw-flow.tsx"),
    route("settings/public-listing", "routes/admin.settings.public-listing.tsx"),
    route("reports/quizzes", "routes/admin.reports.quizzes.tsx"),
    route("reports/outcomes", "routes/admin.reports.outcomes.tsx"),
    route("documents", "routes/admin.documents.tsx"),
    route("audit", "routes/admin.audit.tsx"),
    route("fees", "routes/admin.fees.tsx"),
    route("road-tests", "routes/admin.road-tests.tsx"),
    route("state-coverage", "routes/admin.state-coverage.tsx"),
    route("website", "routes/admin.website.tsx"),
    route("settings/cancellation", "routes/admin.settings.cancellation.tsx"),
  ]),

  route("instructor", "routes/instructor.tsx", [
    index("routes/instructor._index.tsx"),
    route("upcoming", "routes/instructor.upcoming.tsx"),
    route("past", "routes/instructor.past.tsx"),
    route("availability", "routes/instructor.availability.tsx"),
    route("practice-log", "routes/instructor.practice-log.tsx"),
  ]),

  route("family", "routes/family.tsx", [
    index("routes/family._index.tsx"),
    route("lessons", "routes/family.lessons.tsx"),
    route("payments", "routes/family.payments.tsx"),
    route("documents", "routes/family.documents.tsx"),
    route("practice-log", "routes/family.practice-log.tsx"),
    route("certificate/:enrollmentId", "routes/family.certificate.$enrollmentId.tsx"),
  ]),

  route("me", "routes/me.tsx", [
    index("routes/me._index.tsx"),
    route("schedule", "routes/me.schedule.tsx"),
    route("learn", "routes/me.learn._index.tsx"),
    route("learn/:lessonId", "routes/me.learn.$lessonId.tsx"),
    route("checkout/:enrollmentId", "routes/me.checkout.$enrollmentId.tsx"),
    route("find-school", "routes/me.find-school.tsx"),
    route("help", "routes/me.help.tsx"),
  ]),
] satisfies RouteConfig;
